---
title: "Carbon and Nitrogen Metabolism"
author: "Christian Ayala Ortiz"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(ggh4x)
library(ggpubr)
library(tidyverse)
source('scripts/custom_functions.R')
```


# Load data

```{r}
mag_taxonomy <- load_mag_taxonomy() %>% 
  group_by(Phylum) %>% 
  mutate(n = n()) %>% 
  mutate(Phylum_n = str_c(Phylum, ' (', n, ')'))

phyla_colors <- set_names(get_palette('Paired', 18),
                          nm =sort(unique(mag_taxonomy$Phylum)))

cnps_df <- read_csv('data/definitions/metaG_presence_10-31.csv') %>% 
  filter(!str_detect(m_id, 'Trait'),
         def != 'K08094 K13831')

cnps_ids <- read_csv('data/definitions/definitions_C_N_S_P_11_14_24.csv') %>% 
  arrange(Module_id) %>% 
  group_by(Category_1) %>% 
  mutate(order = n():1,
         rx_per_path = n())
```

```{r}
cpns_presence <- cnps_df %>% 
  inner_join(mag_taxonomy, by = 'bin') %>% 
  inner_join(cnps_ids, by = c('m_id' = 'Module_id')) %>% 
  distinct() %>% 
  filter(!(Category_2 %in% c('Methane metabolism')))

cpns_binplot <- cpns_presence %>% 
  filter(present) %>% 
  group_by(Phylum, bin, Category_2, Category_1, rx_per_path) %>% 
  summarise(rx_present = n()) %>% 
  ungroup() %>% 
  mutate(perc_present = rx_present / rx_per_path) %>% 
  ggplot() +
  geom_tile(aes(x = bin,
                y = Category_1,
                fill = perc_present)) +
  facet_grid2(rows = vars(Category_2),
              cols = vars(Phylum),
              scales = 'free',
              space = 'free',
              strip = strip_nested(size = 'variable',
                                   text_x = element_text(angle = 90),
                                   background_x = element_blank(),
                                   clip = 'off'),
              switch = 'y') +
  scale_fill_distiller(palette = 'Oranges', direction = 1,
                       labels = scales::percent) +
  labs(fill = 'Pathway Completeness [%]') +
  theme_bw() +
  theme(panel.grid = element_blank(),
        strip.text.y.left = element_text(angle = 0),
        axis.text.x = element_blank(),
        axis.title = element_blank(),
        strip.placement = 'outer',
        axis.text = element_text(size = 5),
        strip.text = element_text(size = 5),
        legend.text = element_text(size = 5),
        legend.title = element_text(size = 5),
        legend.position = 'bottom',
        axis.ticks.x = element_blank()
  ) 

cpns_binplot

ggsave('output_figures/Ext_Figure_4.svg', cpns_binplot, dpi = 300,
       height = 185, width = 180, units = 'mm')
```


