---
title: "Extended Fig. 5"
author: "Christian Ayala Ortiz"
date: "`r Sys.Date()`"
output: html_document
---

# Load libraries

```{r}
library(tidyverse)
library(ggh4x)
source('scripts/custom_functions.R')
```

# Load data 

```{r}
traits_exp <- read_csv('data/definitions/expression_per_sample_traits_10-31.csv')
traits_def <- read_csv('data/definitions/traits_definitions_update_10_9.csv')
metadata <- load_metadata()
mag_taxonomy <- load_mag_taxonomy()
```

# Data wrangling

```{r}
traits_df <- traits_exp %>% 
  mutate(SampleID = str_replace(SampleID, 'RNA', 'DNA')) %>% 
  inner_join(metadata, by = c('SampleID' = 'sample')) %>% 
  group_by(bin, month, module_id) %>% 
  summarise(mean_expr = mean(expression)) %>% 
  inner_join(traits_def, by = c('module_id' = 'def_id')) %>% 
  filter(!(Category_1 %in% c('Low temperature stress', 'Transcription regulation',
                             'Oxygen limitation', 'pH stress'))) %>% 
  filter(mean_expr > 0) %>% 
  inner_join(mag_taxonomy, by = 'bin') %>% 
  group_by(month, Name, Category_1, Phylum) %>% 
  summarise(mean_expr = mean(mean_expr)) %>% 
  group_by(Phylum, Name, Category_1) %>% 
  mutate(zscore = (mean_expr - mean(mean_expr)) / sd(mean_expr))
  

strip_custom <- strip_nested(text_x = element_text(angle = 90),
                             size = 'variable',
                             clip = 'off')

traits_plot1 <- traits_df %>%
  mutate(Name = str_replace_all(Name, '_', ' '),
         Name = str_replace(Name, 'degradation', 'degrad.'),
         Name = str_replace(Name, 'production', 'prod.'),
         Name = str_replace(Name, 'cyclopropane-fatty-acyl-phospholipid synthase', 'CFA synthase'),
         Name = str_replace(Name, 'lipopolysaccharide', 'LPS'),
         Name = str_replace(Name, 'polysaccharide', 'PS'),
         Name = str_replace(Name, 'Enterobacterial common antigen \\(ECA\\)', 'ECA'),
         Name = str_replace(Name, 'mannosylglucosylglycerate', 'MGG'),
         Name = str_replace(Name, 'choline\\/glycine\\/proline', 'Cho\\/Gly\\/Pro'),
         Name = str_replace(Name, 'glycine betaine', 'GB'),
         Name = str_replace(Name, 'biosynthesis', 'biosynth.'),
         Name = str_replace(Name, 'AhpCF, alkyl hidroxiperoxide reductase', 'AhpCF'),
         Name = str_replace(Name, 'two component system|two-component system', 'two comp. system')) %>% 
  ggplot() +
  geom_tile(aes(y = Name,
                x = month,
                fill = zscore),
            color = 'white',
            linewidth = 0.02) +
  facet_grid2(rows = vars(Category_1),
              cols = vars(Phylum),
              scales = 'free_y',
              space = 'free_y',
              switch = 'y',
              strip = strip_custom,
              labeller = label_wrap_gen(width=10)) +
  scale_fill_distiller(palette = 'RdBu', direction = -1) +
  custom_theme +
  theme(
    # axis.text.y = element_blank(),
    #     axis.ticks.y = element_blank(),
        axis.title = element_blank(),
        strip.text.y.left = element_text(angle = 0),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text = element_text(size = 4.5),
        strip.placement = 'outer',
        legend.position = 'bottom')


traits_plot1

ggsave('output_figures/Ext_figure_5.svg', traits_plot1, dpi = 300, 
       height = 185, width = 180, units = 'mm')
```



