---
title: "Figure 1"
author: "Christian Ayala Ortiz"
date: "`r Sys.Date()`"
output: html_document
---

# Load libraries

```{r}
library(ggpubr)
library(ggh4x)
library(ggnewscale)
library(patchwork)
library(tidyverse)
source('scripts/custom_functions.R')
```

# Load data

```{r}
ndvi <- read_csv('data/environmental_data/ndvi_data.csv') %>% 
  mutate(date = parse_date(`system:time_start`, '%b %d, %Y'))

noaa_data <- read_csv('data/environmental_data/precipitation_data_daily_tucson_11_updated_2021-2023.csv') 

env_data <- read_csv('data/environmental_data/envs_matrix_11_18_24.csv') %>% 
  mutate(sample = str_replace(Sample_ID, 'SAMP', 'DNA-'),
         sample = str_replace(sample, '_', '-'),
         stage = str_replace(stage, '_', ' '))
```

# 1. Environmental variables

## Data wrangling


```{r}
prec <- noaa_data %>% 
  select(LST_DATE, P_DAILY_CALC) %>% 
  mutate(date = ymd(LST_DATE),
         P_DAILY_CALC = ifelse(P_DAILY_CALC < 0, NA, P_DAILY_CALC)) %>% 
  filter(between(date, ymd(20210424), ymd(20220528))) %>% 
  mutate(accum_group = paste0('Group', 
                              rep(str_pad(1:25, 2, pad = '0'), each = 16))) %>% 
  group_by(accum_group) %>% 
  summarise(date = max(date),
            prec_16day = sum(P_DAILY_CALC, na.rm = TRUE))

soil_t <- noaa_data %>% 
  select(LST_DATE, SOIL_TEMP_10_DAILY) %>% 
  mutate(date = ymd(LST_DATE),
         SOIL_TEMP_10_DAILY = ifelse(SOIL_TEMP_10_DAILY < 0, NA, SOIL_TEMP_10_DAILY)) %>% 
  filter(between(date, ymd(20210506), ymd(20220528)))

air_t <- noaa_data %>% 
  select(LST_DATE, T_DAILY_AVG) %>% 
  mutate(date = ymd(LST_DATE),
         T_DAILY_AVG = ifelse(T_DAILY_AVG < 0, NA, T_DAILY_AVG)) %>% 
  filter(between(date, ymd(20210506), ymd(20220528)))


all_vars <- ndvi %>% 
  full_join(prec, by = 'date') %>% 
  full_join(air_t, by = 'date') %>% 
  full_join(soil_t, by = 'date') %>% 
  select(date, NDVI, prec_16day, T_DAILY_AVG, 
         SOIL_TEMP_10_DAILY)

stages <- tribble(
  ~Stage, ~start, ~end,
  'Pre monsoon', ymd(20210506), ymd(20210630),
  'During monsoon', ymd(20210701), ymd(20210831),
  'Post monsoon', ymd(20210901), ymd(20211018),
  'Pre monsoon', ymd(20220524), ymd(20220529)
) %>% 
  mutate(year = year(start))

sampling <- tribble(
  ~sampling, ~date, ~stage,
  'samp1', ymd(20210506), 'Pre monsoon',
  'samp2', ymd(20210615), 'Pre monsoon',
  'samp3', ymd(20210705), 'During monsoon',
  'samp4', ymd(20210715), 'During monsoon',
  'samp5', ymd(20210727), 'During monsoon',
  'samp6', ymd(20210815), 'During monsoon',
  'samp7', ymd(20210915), 'Post monsoon',
  'samp8', ymd(20211018), 'Post monsoon',
  'samp9', ymd(20220528), 'Pre monsoon',
) %>% 
  mutate(stage = factor(stage, levels = c('Pre monsoon', 
                                          'During monsoon', 
                                          'Post monsoon')))

env_data_final <- env_data %>% 
  inner_join(sampling, by = c('sampling', 'stage'))

```

# 2. Generating timeline plots

## Temperature

```{r}
stage_color <- load_colors('stage')

temp_vars <- all_vars %>% 
  select(date, 
         `Air temp.` = T_DAILY_AVG, 
         `Soil temp.` = SOIL_TEMP_10_DAILY) %>% 
  drop_na() %>% 
  filter(!between(date, ymd(20211019), ymd(20220527))) %>% 
  pivot_longer(!date, names_to = 'variable', values_to = 'value') %>% 
  mutate(year = year(date)) 

temp_plot <- temp_vars %>% 
  ggplot() +
  geom_rect(data = stages,
            aes(xmin = start,
                xmax = end,
                ymin = -Inf,
                ymax = Inf,
                fill = Stage),
            alpha = 0.3,
            show.legend = FALSE) +
  scale_fill_manual(values = stage_color) +
  ggnewscale::new_scale_fill() +
  geom_point(aes(x = date, 
                 y = value,
                 color = variable),
             shape = 21,
             size = 1) +
  geom_line(aes(x = date,
                y = value,
                color = variable),
            linewidth = .2) +
  scale_color_manual(values = c('red2', 'purple')) +
  scale_x_date(breaks = seq(from = ymd(20210506), 
                            to = ymd(20220528), by = '16 day'), 
               date_labels = '%b %d, %Y',
               expand = c(0, 0)) +
  facet_grid(cols = vars(year),
             scales = 'free',
             space = 'free') +
  labs(y = 'Temperature\n[°C]') +
  custom_theme +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        legend.title = element_blank(),
        strip.text = element_blank())

temp_plot
```

## Ions

```{r}
metal_vars <- env_data_final %>% 
  select(date,
         Na, Mg, K, Ca, V, Cr, Fe, Co, As, Se) %>% 
  pivot_longer(!date, names_to = 'variable', values_to = 'value') %>% 
  mutate(sep = case_when(variable %in% c('Fe', 'Ca', 'Mg', 'K') ~ 'g1',
                         variable %in% c('Na', 'As', 'V') ~ 'g2',
                         TRUE ~ 'g3')) %>% 
  mutate(year = year(date))


metal_plot <- metal_vars %>% 
  ggplot() +
  geom_rect(data = stages,
            aes(xmin = start,
                xmax = end,
                ymin = -Inf,
                ymax = Inf,
                fill = Stage),
            alpha = 0.3,
            show.legend = FALSE) +
  scale_fill_manual(values = stage_color) +
  ggnewscale::new_scale_fill() +
  geom_point(aes(x = date, 
                 y = value,
                 color = variable),
             shape = 21,
             size = 1) +
  geom_smooth(aes(x = date, 
                  y = value,
                  color = variable),
              se = FALSE,
              linewidth = .2) +
  scale_color_manual(values = get_palette('Dark2', 10)) +
  scale_x_date(breaks = seq(from = ymd(20210506), 
                            to = ymd(20220528), by = '16 day'), 
               date_labels = '%b %d, %Y',
               expand = c(0, 0)) +
  labs(y = 'Concentration\n[ug/g]') +
  facet_grid(rows = vars(sep),
             cols = vars(year),
             scales = 'free',
             space = 'free_x') +
  custom_theme +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.x = element_blank(),
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.text = element_blank())


metal_plot
```

## Carbon and nitrogen

```{r}
cn_vars <- env_data_final %>% 
  select(date,
         total_C, total_N) %>% 
  pivot_longer(!date, names_to = 'variable', values_to = 'value') %>% 
  mutate(sep = case_when(variable %in% c('total_C') ~ 'g1',
                         TRUE ~ 'g2')) %>% 
  mutate(year = year(date))


cn_plot <- cn_vars %>% 
  ggplot() +
  geom_rect(data = stages,
            aes(xmin = start,
                xmax = end,
                ymin = -Inf,
                ymax = Inf,
                fill = Stage),
            alpha = 0.3,
            show.legend = FALSE) +
  scale_fill_manual(values = stage_color) +
  ggnewscale::new_scale_fill() +
  geom_point(aes(x = date, 
                 y = value,
                 color = variable),
             shape = 21,
             size = 1) +
  geom_smooth(aes(x = date, 
                  y = value,
                  color = variable),
              se = FALSE,
              linewidth = .2) +
  scale_color_manual(values = get_palette('Set1', 2)) +
  scale_x_date(breaks = seq(from = ymd(20210506), 
                            to = ymd(20220528), by = '16 day'), 
               date_labels = '%b %d, %Y',
               expand = c(0, 0)) +
  labs(y = 'Concentration\n[%wt]') +
  facet_grid(rows = vars(sep),
             cols = vars(year),
             scales = 'free',
             space = 'free_x') +
  custom_theme +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.text = element_blank())


cn_plot
```

## pH

```{r}
ph_vars <- env_data_final %>% 
  select(date,
         ph_mean) %>% 
  pivot_longer(!date, names_to = 'variable', values_to = 'value') %>% 
  mutate(year = year(date))


ph_plot <- ph_vars %>% 
  ggplot() +
  geom_rect(data = stages,
            aes(xmin = start,
                xmax = end,
                ymin = -Inf,
                ymax = Inf,
                fill = Stage),
            alpha = 0.3,
            show.legend = FALSE) +
  scale_fill_manual(values = stage_color) +
  ggnewscale::new_scale_fill() +
  geom_point(aes(x = date, 
                 y = value,
                 color = variable),
             shape = 21,
             size = 1) +
  geom_smooth(aes(x = date, 
                  y = value,
                  color = variable),
              se = FALSE,
              linewidth = .2) +
  scale_color_manual(values = 'black') +
  scale_x_date(breaks = seq(from = ymd(20210506), 
                            to = ymd(20220528), by = '16 day'), 
               date_labels = '%b %d, %Y',
               expand = c(0, 0)) +
  facet_grid(cols = vars(year),
             scales = 'free',
             space = 'free_x') +
  labs(y = 'pH') +
  custom_theme +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.text = element_blank())


ph_plot
```

## Moisture

```{r}
moist_vars <- env_data_final %>% 
  select(date,
         moisture) %>% 
  pivot_longer(!date, names_to = 'variable', values_to = 'value') %>% 
  mutate(year = year(date))


moist_plot <- moist_vars %>% 
  ggplot() +
  geom_rect(data = stages,
            aes(xmin = start,
                xmax = end,
                ymin = -Inf,
                ymax = Inf,
                fill = Stage),
            alpha = 0.3,
            show.legend = FALSE) +
  scale_fill_manual(values = stage_color) +
  ggnewscale::new_scale_fill() +
  geom_point(aes(x = date, 
                 y = value,
                 color = variable),
             shape = 21,
             size = 1) +
  geom_smooth(aes(x = date, 
                  y = value,
                  color = variable),
              se = FALSE,
              linewidth = .2) +
  scale_color_manual(values = 'steelblue') +
  scale_x_date(breaks = seq(from = ymd(20210506), 
                            to = ymd(20220528), by = '16 day'), 
               date_labels = '%b %d, %Y',
               expand = c(0, 0)) +
  facet_grid(cols = vars(year),
             space = 'free_x',
             scales = 'free') +
  labs(y = 'Moisture') +
  custom_theme +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.text = element_blank())

moist_plot
```

## Precipitation

```{r}
prec_vars <- all_vars %>% 
  select(date, 
         Precipitation = prec_16day) %>% 
  drop_na() %>% 
  filter(!between(date, ymd(20211019), ymd(20220527))) %>% 
  pivot_longer(!date, names_to = 'variable', values_to = 'value') %>% 
  mutate(year = year(date))


prec_plot <- prec_vars %>% 
  ggplot() +
  geom_rect(data = stages,
            aes(xmin = start,
                xmax = end,
                ymin = -Inf,
                ymax = Inf,
                fill = Stage),
            alpha = 0.3,
            show.legend = FALSE) +
  scale_fill_manual(values = stage_color) +
  ggnewscale::new_scale_fill() +
  geom_point(aes(x = date, 
                 y = value,
                 color = variable),
             shape = 21,
             size = 1) +
  geom_line(aes(x = date,
                y = value,
                color = variable),
            linewidth = .2) +
  scale_color_manual(values = 'steelblue') +
  scale_x_date(breaks = seq(from = ymd(20210506), 
                            to = ymd(20220528), by = '16 day'), 
               date_labels = '%b %d, %Y',
               expand = c(0, 0)) +
  labs(y = 'Precipitation\n[mm]') +
  facet_grid2(cols = vars(year),
             space = 'free_x',
             scales = 'free',
             strip = strip_vanilla(clip = 'off')) +
  custom_theme +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.text.y = element_blank())

prec_plot
```

## NDVI

```{r}
ndvi_vars <- all_vars %>% 
  select(date, 
         NDVI) %>% 
  drop_na() %>% 
  pivot_longer(!date, names_to = 'variable', values_to = 'value') %>% 
  filter(!between(date, ymd(20211019), ymd(20220524))) %>%
  mutate(year = year(date))


ndvi_plot <- ndvi_vars %>% 
  ggplot() +
  geom_rect(data = stages,
            aes(xmin = start,
                xmax = end,
                ymin = -Inf,
                ymax = Inf,
                fill = Stage),
            alpha = 0.3,
            show.legend = FALSE) +
  scale_fill_manual(values = stage_color) +
  ggnewscale::new_scale_fill() +
  geom_point(aes(x = date, 
                 y = value,
                 color = variable),
             shape = 21,
             size = 1) +
  geom_line(aes(x = date,
                y = value,
                color = variable),
            linewidth = .2) +
  scale_color_manual(values = 'forestgreen') +
  scale_x_date(breaks = seq(from = ymd(20210506), 
                            to = ymd(20220528), by = '16 day'),
               date_labels = '%b %d, %Y',
               expand = c(0, 0)) +
  facet_grid(cols = vars(year),
             scales = 'free',
             space = 'free_x') +
  labs(y = 'NDVI') +
  custom_theme +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.text = element_blank())


ndvi_plot
```

## Unite figure

```{r}
final <- prec_plot + temp_plot + ndvi_plot + moist_plot + ph_plot +
  cn_plot + metal_plot +
  plot_layout(ncol = 1,
              heights = c(1, 1, 1, 1, 1, 2, 3.5)) &
  theme(axis.title = element_text(size = 7),
        axis.text = element_text(size = 7),
        legend.text = element_text(size = 7),
        legend.justification.right = "left")

final
```

# 3. PCA environmental data

```{r}
env_data <- load_environmental_data() %>% 
  mutate(C_N = total_C / total_N) %>% 
  select(-Na, -total_C, -Mg, -V, -Cr, -Co, -As, -Ca) %>% 
  decostand(., method = 'standardize')

metadata <- load_metadata()

pca_env <- princomp(env_data)

pca_scores <- pca_env$scores %>% 
  as.data.frame() %>% 
  rownames_to_column(var = 'sample') %>% 
  left_join(metadata, by = c('sample' = 'asv_sample'))

month_color <- load_colors('month')
stage_color <- load_colors('stage')

eigen <- factoextra::get_eigenvalue(pca_env)
pc1 <- paste0('PC1 (', round(eigen$variance.percent[1], 2), '%)')
pc2 <- paste0('PC2 (', round(eigen$variance.percent[2], 2), '%)')

pca_plot <- pca_scores %>% 
  ggplot(aes(x = Comp.1,
             y = Comp.2)) +
  geom_point(aes(fill = month),
             shape = 21,
             size = 2) +
  stat_ellipse(aes(color = stage),
               show.legend = FALSE) +
  scale_fill_manual(values = month_color) +
  scale_color_manual(values = stage_color) +
  labs(title = 'PCA - Envs. variables',
       x = pc1,
       y = pc2) +
  custom_theme 

pca_plot
```

# 4. Finalizing figure

```{r}
lay <- "
AC
BC
DC
"

fig1 <- wrap_elements() + wrap_elements() + final + free(pca_plot) +
  plot_layout(design = lay,
              widths = c(1.5, 1)) +
  plot_annotation(tag_levels = list(c('A', 'B', 'D', '', '', '', '', '', '', 'C')))

ggsave('output_figures/incomplete_figure1.svg', fig1, dpi = 300,
       width = 180, height = 185, units = 'mm')
```

