---
title: "Figure 2"
author: "Christian Ayala Ortiz"
date: "`r Sys.Date()`"
output: html_document
---

# Load libraries

```{r setup, include=FALSE}
library(vegan)
library(phyloseq)
library(tidyverse)
library(ggh4x)
library(ggpubr)
library(patchwork)
source('scripts/custom_functions.R')
```

# Loading data

## Microbial data

```{r}
metadata <- load_metadata()

singlem_rplP <- load_singlem_data(which = 'counts',
                                  prev_min_counts = 0,
                                  prev_min_samples = 2,
                                  normalize_sum = FALSE)

set.seed(123)
singlem_rarefied <- rrarefy(singlem_rplP, 800) %>% 
  as.data.frame()


singlem_taxonomy <- load_singlem_taxonomy() %>% 
  mutate(Phylum_lump = fct_lump_n(Phylum, 8, w = coverage),
         Class = ifelse(is.na(Class), glue::glue('Unassigned class of {Phylum}'), Class),
         Class_lump = fct_lump_n(Class, 12, w = coverage))
```

## Organic matter data

```{r}
fticr_pos <- load_fticr_data(mode = 'positive',
                             prev_min_counts = 0,
                             prev_min_samples = 2,
                             normalize_sum = FALSE)

fticr_annot_pos <- load_fticr_annot(mode = 'positive')
```

## Color vectors

```{r}
phyl_color <- set_names(
  c(ggpubr::get_palette('Paired', 8), 'gray60'),
  nm = levels(singlem_taxonomy$Phylum_lump)
)

class_color <- set_names(
  c(ggpubr::get_palette('Paired', 12), 'gray60'),
  nm = levels(singlem_taxonomy$Class_lump)
)

month_color <- load_colors('month')
stage_color <- load_colors('stage')
```

# Taxonomic profiles

## SingleM

```{r}
singlem_ra <- singlem_taxonomy %>% 
  group_by(sample) %>% 
  mutate(r_abundance = coverage / sum (coverage)) %>% 
  group_by(sample, Class_lump) %>% 
  summarise(r_abundance = sum(r_abundance)) %>% 
  inner_join(metadata, by = c('sample' = 'asv_sample'))

singlem_tax_plot <- singlem_ra %>%  
  group_by(Class_lump, month) %>%
  summarise(r_abundance = mean(r_abundance)) %>%
  ggplot() +
  geom_col(aes(x =month,
               y = r_abundance,
               fill = Class_lump),
           color = 'black',
           linewidth = .2) +
  scale_fill_manual(values = class_color) +
  scale_y_continuous(labels = scales::percent) +
  labs(title = 'Taxonomy profile - SingleM',
       y = 'Relative Abundance',
       fill = 'Class') +
  guides(fill = guide_legend(nrow = 5)) +
  custom_theme +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = 'bottom',
        legend.key.spacing.y = unit(.01, 'lines'),
        legend.key.spacing.x = unit(.01, 'lines'),
        legend.key.size = unit(.5, 'lines'),
        legend.title.position = 'top',
        legend.box.spacing = unit(0, 'lines'))


singlem_tax_plot
```

# Organic matter profiles

## FTICR positive

### Elemental Composition

```{r}
fticr_elcomp_pos <- fticr_pos %>% 
  rownames_to_column(var = 'sample') %>% 
  pivot_longer(!sample, names_to = 'Mass', values_to = 'intensity') %>% 
  filter(sample %in% metadata$asv_sample) %>% 
  mutate(Mass = as.numeric(Mass)) %>% 
  group_by(sample) %>% 
  inner_join(fticr_annot_pos, by = 'Mass') %>%
  mutate(perc = intensity/sum(intensity)) %>%
  inner_join(metadata, by = c('sample' = 'asv_sample')) %>%
  group_by(sample, month, El_comp) %>% 
  summarise(perc = sum(perc)) %>% 
  group_by(month, El_comp) %>%
  summarise(perc = mean(perc))

fticr_elcomp_pos_plot <- fticr_elcomp_pos %>% 
  ggplot() +
  geom_col(aes(x = month,
               y = perc,
               fill = El_comp),
           color = 'black',
           linewidth = .2) +
  scale_fill_manual(values = get_palette('Set2', 8)) +
  scale_y_continuous(labels = scales::percent) +
  labs(title = 'Elemental Composition - FTICR-MS',
       y = 'Relative Abundance',
       fill = 'Element Composition') +
  guides(fill = guide_legend(nrow = 5)) +
  custom_theme +
  theme(axis.title.x = element_blank(),
        legend.position = 'bottom',
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.key.spacing.y = unit(.01, 'lines'),
        legend.key.spacing.x = unit(.01, 'lines'),
        legend.key.size = unit(.3, 'lines'),
        legend.title.position = 'top',
        legend.box.spacing = unit(0.1, 'lines'))

fticr_elcomp_pos_plot
```

## SingleM

```{r}
metadata_singlem <- metadata %>% 
  filter(asv_sample %in% rownames(singlem_rplP))

singlem_bray <- vegdist(singlem_rarefied[metadata_singlem$asv_sample,], method = 'bray')

# group_factor <- metadata_singlem %>% 
#   pull(month)
# 
# bd <- betadisper(singlem_bray, group_factor)
# 
# anova(bd)
# permutest(bd)

singlem_permanova <- adonis2(singlem_bray ~ month,
                             data = metadata_singlem)
singlem_permanova

singlem_phylo <- phyloseq(sample_data(metadata %>% 
                                        filter(asv_sample %in% rownames(singlem_rplP)) %>% 
                                        column_to_rownames(var = 'asv_sample')),
                          otu_table(singlem_rarefied, taxa_are_rows = FALSE))

singlem_ord <- ordinate(singlem_phylo, method = "MDS", distance = "bray")

singlem_pcoa_plot <- plot_ordination(singlem_phylo, singlem_ord, justDF = TRUE) %>% 
  ggplot(aes(x = Axis.1,
             y = Axis.2)) +
  geom_point(aes(fill = month),
             size = 2,
             shape = 21) +
  # ggforce::geom_mark_ellipse(aes(color = month),
  #                            show.legend = FALSE) +
  annotate('label',label = str_c('PERMANOVA\nMonth p-value = ', singlem_permanova$`Pr(>F)`[1],
                                 '\nMonth R2 = ', round(singlem_permanova$R2[1], 2)),
           x = 0.2,
           y = 0.15,
           size = 1.5,
           hjust = 0,
           vjust = 0) +
  scale_fill_manual(values = month_color) +
  # scale_color_manual(values = stage_color) +
  scale_x_continuous(limits = c(-0.4, 0.6)) +
  labs(title = 'PCoA Ordination - SingleM',
       x = paste0('Axis.1 [', round(singlem_ord$values$Relative_eig[1] * 100, 1), '%]'),
       y = paste0('Axis.2 [', round(singlem_ord$values$Relative_eig[2] * 100, 1), '%]'),
       fill = 'Month') +
  custom_theme +
  theme(legend.position = 'none')

singlem_pcoa_plot
```


## FTICR data

```{r}
metadata_fticr <- metadata %>% 
  filter(asv_sample %in% rownames(fticr_pos))

fticr_jaccard <- decostand(fticr_pos[metadata_fticr$asv_sample,], method = 'pa') %>% 
  vegdist(, method = 'jaccard')

fticr_permanova <- adonis2(fticr_jaccard ~ month,
                           data = metadata_fticr)
fticr_permanova

# group_factor <- metadata_fticr %>% 
#   pull(month)
# 
# bd <- betadisper(fticr_bray, group_factor)
# 
# anova(bd)
# permutest(bd)

nmds_fticr <- metaMDS(fticr_jaccard,
                      distance = 'jaccard',
                      k = 2,
                      try = 500, 
                      maxit = 999,
                      wascores = TRUE)

nmds_scores_fticr <- as.data.frame(vegan::scores(nmds_fticr)) %>% 
  rownames_to_column(var = 'asv_sample') %>% 
  inner_join(metadata_fticr, by = 'asv_sample')

nmds_plot_fticr <- nmds_scores_fticr %>% 
  ggplot(aes(x = NMDS1,
             y = NMDS2)) +
  geom_point(aes(fill = month),
             shape = 21,
             size = 2) +
  # stat_density_2d(aes(color = stage), 
  #                 linewidth = 1, contour = TRUE, alpha = 0.5) +
  # ggforce::geom_mark_ellipse(aes(color = stage),
  #                            show.legend = FALSE) +
  scale_fill_manual(values = month_color) +
  # scale_color_manual(values = stage_color) +
  annotate('label',label = str_c('PERMANOVA\nMonth p-value = ', fticr_permanova$`Pr(>F)`[1],
                                 '\nMonth R2 = ', round(fticr_permanova$R2[1], 2),
                                 '\nNMDS stress = ', round(nmds_fticr$stress, 2)),
           x = 0.25,
           y = -0.4,
           size = 1.5,
           hjust = 0,
           vjust = 0) +
  labs(title = 'NMDS Ordination - FTICR-MS') +
  custom_theme +
  theme(legend.position = 'none')

nmds_plot_fticr
```

## Ordination legend

```{r}
for_legend2 <- metadata %>% 
  ggplot() +
  geom_point(aes(x = 2, y = 3,
                 fill = month),
             shape = 21,
             size = 2) +
  scale_fill_manual(values = month_color) +
  guides(fill = guide_legend(nrow = 2)) +
  labs(fill = 'Month') +
  theme_bw() +
  theme(legend.position = 'bottom',
        text = element_text(size = 7),
        legend.key.spacing.y = unit(.01, 'lines'),
        legend.key.spacing.x = unit(.01, 'lines'),
        legend.key.size = unit(.5, 'lines'),
        legend.title.position = 'left')

leg_ord <- get_legend(for_legend2)
```

# Alpha diversity

```{r}
fticr_alpha <- phyloseq::otu_table(round(fticr_pos), taxa_are_rows = FALSE) %>% 
  phyloseq::estimate_richness(.) %>% 
  select(Observed, Chao1, ACE) %>% 
  rownames_to_column(var = 'sample') %>% 
  pivot_longer(c(Observed, Chao1, ACE), names_to = 'idx', values_to = 'value')  %>% 
  mutate(sample = str_replace(sample, '\\.', '-'),
         dataset = 'FTICR')

singlem_split <- read_tsv('data/singlem_output/reads_otu_table.tsv') %>% 
  split(.$gene) 

singlem_alpha <- imap(singlem_split, function(df, gene){
  
  proc <- df %>% 
    filter(!str_detect(sample, 'S0'))  %>% 
    mutate(sample = str_remove(sample, '_L.*'))  %>% 
    mutate(sample = str_remove(sample, '_S.*')) %>%  
    group_by(sample, sequence) %>%
    summarise(value = sum(num_hits)) %>%
    ungroup() %>% 
    inner_join(metadata, by = 'sample') %>% 
    select(asv_sample, sequence, value) %>% 
    pivot_wider(names_from = sequence, values_from = value, values_fill = 0) %>% 
    column_to_rownames(var = 'asv_sample') %>% 
    rrarefy(., 800) %>% 
    phyloseq::otu_table(., taxa_are_rows = FALSE) %>% 
    phyloseq::estimate_richness(.) %>% 
    select(Observed, Chao1, ACE) %>% 
    rownames_to_column(var = 'sample') %>% 
    pivot_longer(c(Observed, Chao1, ACE), names_to = 'idx', values_to = 'value')  %>% 
    mutate(sample = str_replace_all(sample, '\\.', '-')) %>% 
    mutate(gene = gene)
  
  return(proc)
  
})

singlem_alpha_summ <- reduce(singlem_alpha, rbind) %>% 
  group_by(sample, idx) %>% 
  summarise(value = mean(value)) %>% 
  mutate(dataset = 'SingleM')
```


```{r}

stages <- tribble(
  ~Stage, ~start, ~end,
  'Pre monsoon', -Inf, 1.5,
  'During monsoon', 1.5, 5.5,
  'Post monsoon', 5.5, 6.5,
  'Pre monsoon', 6.5, Inf
) %>% 
  mutate(Stage = factor(Stage, levels = c('Pre monsoon',
                                          'During monsoon',
                                          'Post monsoon')))

stages_ready <- rbind(stages, stages, stages, stages) %>% 
  mutate(dataset = rep(c('SingleM', 'FTICR'), each = 8),
         idx = rep(c(rep('Observed richness', 4), rep('Chao1 index', 4)), 2))

new_alpha_plot <- rbind(singlem_alpha_summ, fticr_alpha) %>% 
  inner_join(metadata, by = c('sample' = 'asv_sample')) %>% 
  mutate(idx = factor(idx, levels = c('Observed', 'Shannon', 'Chao1', 'ACE')),
         idx = fct_recode(idx, `Observed richness` = 'Observed', `Chao1 index` = 'Chao1'), 
         dataset = factor(dataset, levels = c('ASV', 'SingleM', 'FTICR'))) %>% 
  filter(dataset %in% c('SingleM', 'FTICR'),
         idx != 'ACE') %>% 
  ggplot() +
  geom_rect(data = stages,
            aes(xmin = start,
                xmax = end,
                ymin = -Inf,
                ymax = Inf,
                fill = Stage),
            alpha = 0.3) +
  scale_fill_manual(values = stage_color) +
  ggnewscale::new_scale_fill() +
  geom_boxplot(aes(x = month,
                   y = value,
                   fill = dataset),
               linewidth = 0.2,
               outlier.size = 0.5,
               show.legend = FALSE) +
  facet_grid2(rows = vars(idx),
              cols = vars(dataset),
              scales = 'free',
              independent = 'y',
              switch = 'y') +
  scale_fill_brewer(palette = 'Dark2') +
  custom_theme +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title = element_blank(), 
        legend.position = 'bottom',
        strip.background = element_blank(),
        strip.placement = 'outer',
        legend.title.position = 'top',
        legend.key.spacing.y = unit(.01, 'lines'),
        legend.key.spacing.x = unit(.01, 'lines'),
        legend.key.size = unit(.5, 'lines'),
        legend.box.spacing = unit(0, 'lines'))

new_alpha_plot
```

# 2. Other sites data

## Load data

```{r}
metadata_reads <- read_csv('data/metadata_reads.csv')

dist_files <- list.files('data/mash_distances/',
                         pattern = 'dist',
                         full.names = TRUE)

mash_res <- purrr::map(dist_files, ~read_tsv(.x, col_names = FALSE))

mash_df <- purrr::reduce(mash_res, rbind) %>% 
  mutate(across(.cols = c(X1, X2), ~(str_remove(.x, 'fil.*/'))),
         across(.cols = c(X1, X2), ~(str_remove(.x, 'add.*/'))),
         across(.cols = c(X1, X2), ~(str_remove(.x, '_L.*')))) %>% 
  filter(!if_any(c(X1, X2), ~str_detect(.x, 'S0'))) %>% 
  select(-X4, -X5) %>% 
  pivot_wider(names_from = X2, values_from = X3) %>% 
  column_to_rownames(var = 'X1')
```

## Calculating ordination

```{r}
set.seed(123)
mash_dist <- as.dist(mash_df[metadata_reads$sample, metadata_reads$sample])

nmds_reads <- metaMDS(mash_dist,
                      distance = 'bray',
                      k = 2,
                      try = 500, 
                      maxit = 999,
                      wascores = TRUE)

```

## Plotting ordination

```{r}
nmds_scores <- as.data.frame(scores(nmds_reads)) %>% 
  rownames_to_column(var = 'sample') %>% 
  left_join(metadata_reads, by = 'sample')

nmds_plot_mash <- nmds_scores %>% 
  ggplot() +
  geom_point(aes(x = NMDS1,
                 y = NMDS2,
                 fill = Location),
             size = 1.7,
             shape = 21,
             alpha = 0.6) +
  # ggforce::geom_mark_ellipse(aes(x = NMDS1,
  #                                y = NMDS2,
  #                                group = dataset),
  #                            linewidth = .2) +
  scale_fill_manual(values = ggpubr::get_palette('Dark2', 8)) +
  guides(fill = guide_legend(ncol = 2)) +
  #labs(title = 'MASH distances between different datasets') +
  custom_theme +
  theme(legend.position = 'bottom',
        legend.key.spacing.y = unit(.01, 'lines'),
        legend.key.spacing.x = unit(.01, 'lines'),
        legend.key.size = unit(.5, 'lines'),
        legend.title.position = 'top',
        legend.box.spacing = unit(0, 'lines'))

nmds_plot_mash
```

# Figure 2

```{r}
layout <- "
ABG
DEC
FFC
"

fig2 <- singlem_tax_plot + fticr_elcomp_pos_plot + free(new_alpha_plot) +
  singlem_pcoa_plot + nmds_plot_fticr + leg_ord + nmds_plot_mash +
  plot_layout(design = layout, 
              heights = c(1.5, 1, .07),
              widths = c(1, 1 , 1)) + 
  plot_annotation(tag_levels = list(c('A', 'B', 'F', 'D', 'E', '', 'C'))) &
  theme(text = element_text(size = 7),
        # plot.title = element_blank(),
        plot.margin = unit(c(0.2, 0.2, 0.2, 0.2), 'lines'))

fig2

ggsave('output_figures/Figure_2.svg', fig2, dpi = 300,
       width = 180, height = 150, units = 'mm')
```

